version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
          - "antlr4-python3-runtime"
          - "beautifulsoup4"
          - "furo"
          - "pyright"
          - "pytest-cov"
          - "pytest-regressions"
          - "pytest"
          - "PyYAML"
          - "sphinx_design"
          - "sphinx-autobuild"
          - "sphinx"
          - "sphinxcontrib-svg2pdfconverter"
          - "syntax-diagrams"
          - "sybil"
          - "tox"
          - "tox-uv"
      style:
        patterns:
          - "prek"
          - "ruff"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pre-commit:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-actions:
        patterns:
          - "*"
